// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesTelegramBotApp;

#nullable disable

namespace MoviesTelegramBotApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240718131029_BudgetToString")]
    partial class BudgetToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesTelegramBotApp.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("MoviesTelegramBotApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BehindTheScene")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Budget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestFactsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BehindTheScene = "https://www.youtube.com/watch?v=m15YteEQC7k",
                            Budget = "100000",
                            Country = "USA",
                            Description = "desc 1",
                            GenreId = 1,
                            ImageUrl = "https://i.pinimg.com/736x/f8/46/e4/f846e4d7aa3aa6b7c82799e4745f8ab1.jpg",
                            InterestFactsUrl = "https://www.youtube.com/watch?v=ID_TNr5yoHE",
                            MovieUrl = "https://www.youtube.com/watch?v=jaJuwKCmJbY",
                            Title = "Die hard"
                        },
                        new
                        {
                            Id = 2,
                            BehindTheScene = "https://www.youtube.com/watch?v=iWPWZNfh-To",
                            Budget = "1000000",
                            Country = "USA",
                            Description = "desc 2",
                            GenreId = 2,
                            ImageUrl = "https://i.pinimg.com/originals/61/fa/cb/61facb2dbfa0f558c8be590d93813af5.jpg",
                            InterestFactsUrl = "https://www.youtube.com/watch?v=zqAgauSv7AE",
                            MovieUrl = "https://www.youtube.com/watch?v=LZl69yk5lEY",
                            Title = "The Mask"
                        },
                        new
                        {
                            Id = 3,
                            BehindTheScene = "https://www.youtube.com/watch?v=M2Lul33Oypw",
                            Budget = "200000",
                            Country = "USA",
                            Description = "desc 3",
                            GenreId = 3,
                            ImageUrl = "https://i.pinimg.com/736x/39/66/3b/39663baaa2f92e10fa3f6757ce9b4d37.jpg",
                            InterestFactsUrl = "https://www.youtube.com/watch?v=tHQEimbxdRE",
                            MovieUrl = "https://www.youtube.com/watch?v=PLl99DlL6b4",
                            Title = "The Shawshank redemption"
                        },
                        new
                        {
                            Id = 4,
                            BehindTheScene = "https://www.youtube.com/watch?v=3CuFPurGYDk",
                            Budget = "300000",
                            Country = "USA",
                            Description = "desc 4",
                            GenreId = 3,
                            ImageUrl = "https://i.pinimg.com/222x/70/2f/95/702f957e27890efd7f65d40a04c1915d.jpg",
                            InterestFactsUrl = "https://www.youtube.com/shorts/N6Nv5Z8U4P0",
                            MovieUrl = "https://www.youtube.com/watch?v=jcDD2-s4vWA",
                            Title = "Point Break"
                        },
                        new
                        {
                            Id = 5,
                            BehindTheScene = "https://www.youtube.com/watch?v=MBShyOajLcg",
                            Budget = "450000",
                            Country = "USA",
                            Description = "desc 5",
                            GenreId = 1,
                            ImageUrl = "https://i.pinimg.com/736x/8d/ae/66/8dae66323e077860ea2ab571edede26c.jpg",
                            InterestFactsUrl = "https://www.youtube.com/watch?v=amTSmyikwlY",
                            MovieUrl = "https://www.youtube.com/watch?v=CRRlbK5w8AE",
                            Title = "Terminator"
                        });
                });

            modelBuilder.Entity("MoviesTelegramBotApp.Models.Movie", b =>
                {
                    b.HasOne("MoviesTelegramBotApp.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MoviesTelegramBotApp.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
